Implement cache service
companieshouse/chs-streaming-api-cache pull request #4
Opened 2020-10-14 16:43 UTC by dlloyd1-ch

Add main function to initialise and start service.

Added configuration for client and redis services.

2020-10-14 17:22 UTC, dlgroves-ch requested changes

2020-10-14 17:22 UTC, dlgroves-ch commented on config/config.go
> +	return cfg.BindAddr()
Causes a stack overflow error on my machine

2020-10-14 17:22 UTC, dlgroves-ch commented on config/config.go
> +	return cfg.CertFile()
Causes a stack overflow error on my machine

2020-10-14 21:02 UTC, dlgroves-ch reviewed
The request handler also needs to append a newline to the outgoing message else it won't appear in the response.

2020-10-14 21:02 UTC, dlgroves-ch commented on service/service.go
> +	go s.broker.Run()
We also need to start the client here:
```golang
go s.client.Connect()
```

2020-10-15 08:53 UTC, dlloyd1-ch commented on config/config.go
> +	return cfg.BindAddr()
Fixed

2020-10-15 08:53 UTC, dlloyd1-ch commented on config/config.go
> +	return cfg.CertFile()
Fixed

2020-10-15 16:53 UTC, dlgroves-ch approved these changes

2020-10-16 12:48 UTC, merged