Implement offset functionality
companieshouse/chs-streaming-api-cache pull request #5
Opened 2020-10-15 12:26 UTC by dlloyd1-ch

2020-10-15 17:00 UTC, dlgroves-ch requested changes

2020-10-15 17:00 UTC, dlgroves-ch commented on handlers/handler.go
> +	if o > 0 {
We need to continue serving the latest offsets after the range has been returned:
```golang
if o > 0 {
    h.processOffset(writer, request)
}
h.processHttp(writer, request)
```

2020-10-15 17:00 UTC, dlgroves-ch commented on offset/offset.go
> +	o, err := strconv.Atoi(offset)
Recommend using `strconv.ParseInt(offset, 10, 64)` here in line with Kafka.

2020-10-19 08:40 UTC, kinpang-CH approved these changes

2020-10-19 10:22 UTC, dlgroves-ch approved these changes

2020-10-21 08:32 UTC, dlgroves-ch approved these changes

2020-10-21 09:33 UTC, kinpang-CH approved these changes

2020-10-21 09:52 UTC, merged